# Generated by Django 4.1 on 2023-08-01 14:21

import cinema.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_movie_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='image',
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_image',
            field=models.ImageField(null=True, upload_to=cinema.models.movie_image_file_path),
        ),
        migrations.AddField(
            model_name='moviesession',
            name='image',
            field=models.ImageField(null=True, upload_to=cinema.models.movie_image_file_path),
        ),
    ]
