# Generated by Django 4.1 on 2023-03-21 12:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("cinema", "0002_movie_image")]

    operations = [
        migrations.RenameField(
            model_name="movie", old_name="image", new_name="movie_image"
        )
    ]
