# Generated by Django 4.1 on 2022-11-25 12:06

import cinema.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_movie_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviesession',
            name='image',
            field=models.ImageField(null=True, upload_to=cinema.models.movie_image_file_path),
        ),
    ]
