# Generated by Django 4.2.7 on 2024-03-06 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_movie_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='image',
            new_name='images',
        ),
    ]
