# Generated by Django 4.1 on 2023-07-25 15:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cinema", "0002_movie_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="image",
            field=models.ImageField(null=True, upload_to="create_image_movie_path"),
        ),
    ]
