# Generated by Django 4.1 on 2022-11-23 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_movie_imane'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='imane',
            new_name='image',
        ),
    ]
