# Generated by Django 4.1 on 2023-07-02 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cinema", "0002_movie_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="moviesession",
            name="movie_image",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movie_sessions",
                to="cinema.movie",
            ),
        ),
    ]
