# Generated by Django 4.1 on 2023-08-01 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_remove_movie_image_movie_movie_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='movie_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='moviesession',
            old_name='image',
            new_name='movie_image',
        ),
    ]
