# Generated by Django 4.2.8 on 2023-12-27 15:34

import cinema.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cinema", "0003_alter_movie_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="image",
            field=models.ImageField(
                default=False, null=True, upload_to=cinema.models.movie_image_file_path
            ),
        ),
    ]
