# Generated by Django 4.1 on 2023-04-11 10:27

import cinema.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cinema", "0003_alter_movie_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="image",
            field=models.ImageField(null=True, upload_to=cinema.models.path_of_image),
        ),
    ]
