# Generated by Django 4.1 on 2022-11-25 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_moviesession_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviesession',
            name='image',
        ),
    ]
