# Generated by Django 4.2.3 on 2023-07-06 08:19

import cinema.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cinema", "0004_rename_movie_image_movie_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=cinema.models.movie_image_file_path
            ),
        ),
    ]
