# Generated by Django 4.1 on 2023-04-11 20:57

import cinema.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cinema", "0004_remove_movie_image_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="image",
            field=models.ImageField(
                null=True, upload_to=cinema.models.create_image_path
            ),
        ),
        migrations.DeleteModel(
            name="Image",
        ),
    ]
