# Generated by Django 4.1 on 2023-04-11 21:14

import cinema.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cinema", "0005_movie_image_delete_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=cinema.models.create_image_path,
            ),
        ),
    ]
