# Generated by Django 4.1 on 2022-12-11 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_user_managers_remove_user_username_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.CharField(
                max_length=24, unique=True, verbose_name="email address"
            ),
        ),
    ]
