# Generated by Django 4.1 on 2022-10-27 11:01

from django.db import migrations
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_user_email_alter_user_username"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", user.models.UserManager()),
            ],
        ),
    ]
