# Generated by Django 4.1 on 2024-03-03 12:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_user_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
