# Generated by Django 4.0.4 on 2022-07-19 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
